"""Added other columns to Blog_stat

Revision ID: 09fcb824fa37
Revises: 4e1c0c10995f
Create Date: 2024-12-18 17:07:54.874542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fcb824fa37'
down_revision = '4e1c0c10995f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_blocked', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('posts_pending_approval', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_stats', schema=None) as batch_op:
        batch_op.drop_column('posts_pending_approval')
        batch_op.drop_column('user_blocked')

    # ### end Alembic commands ###
