"""Added other timestamp to Blog_stat

Revision ID: 4b92288f6b4a
Revises: 09fcb824fa37
Create Date: 2024-12-18 17:19:41.411887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b92288f6b4a'
down_revision = '09fcb824fa37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_stats', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
