"""Initial Migrations

Revision ID: 95b14b91cb52
Revises: 
Create Date: 2024-12-11 14:22:14.428671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b14b91cb52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=700), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_total', sa.Integer(), nullable=True),
    sa.Column('user_active_total', sa.Integer(), nullable=True),
    sa.Column('posts_approved', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=30), nullable=False),
    sa.Column('picture', sa.String(length=700), nullable=False),
    sa.Column('picture_source', sa.String(length=700), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('about', sa.String(length=385), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.Column('date_to_post', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('intro', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('picture_v', sa.String(length=200), nullable=True),
    sa.Column('picture_v_source', sa.String(length=500), nullable=True),
    sa.Column('picture_h', sa.String(length=200), nullable=True),
    sa.Column('picture_h_source', sa.String(length=500), nullable=True),
    sa.Column('picture_s', sa.String(length=200), nullable=True),
    sa.Column('picture_s_source', sa.String(length=500), nullable=True),
    sa.Column('picture_alt', sa.String(length=200), nullable=True),
    sa.Column('meta_tag', sa.String(length=200), nullable=True),
    sa.Column('title_tag', sa.String(length=200), nullable=True),
    sa.Column('admin_approved', sa.Boolean(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['blog_user.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['blog_theme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_posts')
    op.drop_table('blog_user')
    op.drop_table('blog_theme')
    op.drop_table('blog_stats')
    op.drop_table('blog_contact')
    # ### end Alembic commands ###
