"""added posts_total to Blog_stat

Revision ID: ce1634334de1
Revises: 4b92288f6b4a
Create Date: 2024-12-18 18:34:04.317624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1634334de1'
down_revision = '4b92288f6b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posts_total', sa.Integer(), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_stats', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('posts_total')

    # ### end Alembic commands ###
